### ISSUE TITLE
serverless.yml update

### ISSUE THREAD

**Issue by Aivenho** [faizanbashir/python-ses-dynamodb-contactform#1]
Had to add in serverless.yml file after runtime: python2.7 the 
`environment:`
`    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}`
to deploy it sucessfully

**Comment by faizanbashir** [comment]
This [commit](https://github.com/faizanbashir/python-ses-dynamodb-contactform/commit/7c053ee73ab3d75ccc2e1443f26f7b0ff2cf0e4c) had added the `DYNAMODB_TABLE` env variable, dunno why you had to add it.
